language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

branches:
  only:
    - master
    - develop

install:
  - composer self-update
  - composer update --prefer-source $DEPENDENCIES

before_script:
  - mkdir -p build/coverage
  - tests/travis/sphinx-setup.sh

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls

notifications:
  email: false

  matrix:
  fast_finish: true
  allow_failures:
    - php: 7
